version: "3"

services:
  postgresql:
    image: postgres
    restart: always
    container_name: simplechat_dev
    ports:
      - "5656:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simplechat_dev
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:

